sudo: false
language: cpp

env:
  global:
    - BIN=stm32flash

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: require
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env:
        - MATRIX_EVAL="COMPILER=clang++"

install:
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    sudo apt update -qq;
    sudo apt install build-essential git;
  fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    brew update > /dev/null;
  fi
- export ARTIFACT=${BIN}_${TRAVIS_OS_NAME}.zip;

script:
- make;
- ls;
- find . | grep stm32flash;
- zip ${ARTIFACT} stm32flash;

after_success:
- export GITHUB_TOKEN=$github_token
- wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    bash ./upload.sh $ARTIFACT;
  fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then bash ./upload.sh $ARTIFACT; fi